name: Tests

on:
  create:
  workflow_dispatch:

jobs:
  go-tests:
    name: Tests
    if: github.event_name == 'workflow_dispatch' || github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: make tests
